name: active_storage
description: Send files to Rails Active Storage using direct upload
version: 0.0.1
author: Algonauti <account@algonauti.com>
homepage: https://www.algonauti.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  http: ^0.12.0+2
  crypto: ^2.0.6

dev_dependencies:
  test: ^1.6.0
