name: active_storage
description: Send files to Rails Active Storage using direct upload
version: 0.0.1
author: Algonauti
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.6.0
